import javax.swing.Box;
import javax.swing.JPanel;

import java.awt.*;
// import java.io.File;
// import java.io.IOException;
// import java.util.Scanner;

// import itemviewPkg.ItemView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jay
 */

public class TestDashboard extends javax.swing.JFrame {

    String username, userID, name;
    // private String itemId, itemName, itemPrice, itemImg, itemDuedate, itemOwner;
    Util obj = new Util("item_access");
    static int count = 5;

    /**
     * Creates new form Dashboard
     */
    public TestDashboard() {
        initComponents();
        this.setSize(700, 700);
    }
    public void getData(String username, String userId, String name)
    {
        this.username = username;
        this.userID = userId;
        this.name = name;
        // jLabel1.setText("Hi, " + name);
    }

    // @Override
    // public Dimension getPreferredSize() {
    //     GraphicsConfiguration config = getGraphicsConfiguration();
    //     Insets  insets = Toolkit.getDefaultToolkit().getScreenInsets(config);
    //     Dimension size = config.getBounds().getSize();
    //     size.width  -= insets.left + insets.right;
    //     size.height -= insets.top  + insets.bottom;
    //     size.width   = size.width / 3;
    //     size.height  = size.height * 2 / 3;
    //     return size;
    // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(7, 170, 600, 340);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 110, 75, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // for(int i=0; i<10; i++)
        // {
        //     JLabel l = new JLabel("hello");
        //     jPanel2.add(l);
        //     l.setBounds(5, count, 180, 150);
        //     count += 160;
        // }
        JPanel l = new JPanel();
        l.setBackground(Color.BLUE);
        l.setMaximumSize(new Dimension(Integer.MAX_VALUE, 180));
        l.setPreferredSize(new Dimension(150, 150));
        // l.setPreferredSize(new Dimension(100, 400));
        // l.setSize(new Dimension(180, 150));
        jPanel2.add(Box.createRigidArea(new Dimension(0, 10)));
        jPanel2.add(l);
        // jPanel2.add(l);
        // l.setBounds(5, count, 180, 150);
        count += 160;
        jPanel2.setPreferredSize(null);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}


// void listAllItems() throws IOException
    // {
    //     // String ipath =  System.getProperty("user.dir") + File.separator + "AuctionSys Data" + File.separator + "ItemData.txt";
    //     File itemData = new File(System.getProperty("user.dir") + File.separator + "AuctionSys Data" + File.separator + "ItemData.txt");
    //     if(itemData.exists() && itemData.length() > 0)
    //     {
    //         Scanner list = new Scanner(itemData);
    //         int count = 5;
    //         while(list.hasNextLine())
    //         {
    //             final String lineFromFile = list.nextLine();
    //             Scanner match = new Scanner(lineFromFile);
    //             match.useDelimiter("::");
    //             itemId = match.next();
    //             itemName = obj.decrypt(match.next(), itemId);
    //             itemPrice = obj.decrypt(match.next(), itemId);
    //             itemDuedate = obj.decrypt(match.next(), itemId);
    //             itemImg = match.next();
    //             itemOwner = match.next().trim();
    //             match.close();

    //             // ItemView newItem = new ItemView(itemId, itemName, itemPrice, itemImg, itemDuedate, username, itemOwner);
    //             // newItem.checkDaysleft();
    //             // jPanel1.add(newItem);
    //             // newItem.setBounds(5, count, 480, 180);
    //             count += 185;
    //         }
    //         list.close();
    //     }
    // }